version: "3.5"
networks:
  consul:
    external: true
  default:
services:
  admin:
    image: xhhscau/scau-bbs/scau-bbs-admin:1.0-snapshot
    networks:
      - default
      - consul
    ports:
      - "8080:8080"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"

  chat:
    image: xhhscau/scau-bbs/scau-bbs-chat:1.0-snapshot
    networks:
      - default
      - consul
    ports:
      - "8084:8084"
      - "8083:8083"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"

  portal:
    image: xhhscau/scau-bbs/scau-bbs-portal:1.0-snapshot
    networks:
      - default
      - consul
    ports:
      - "8082:8082"
    restart: unless-stopped
    logging:
       driver: "json-file"
       options:
          max-size: "10M"
          max-file: "10"

  rest:
    image: xhhscau/scau-bbs/scau-bbs-rest:1.0-snapshot
    networks:
      - default
      - consul
    ports:
      - "8081:8081"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
