version: "3.5"
volumes:
  consul-server-1:
  consul-server-2:
  consul-server-3:

networks:
  consul:
    name: consul

services:
  consul-agent-1: &consul-agent
    image: consul:latest
    networks:
      - consul
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"
    restart: unless-stopped

  consul-agent-2:
    <<: *consul-agent

  consul-agent-3:
    <<: *consul-agent

  consul-server-1: &consul-server
    <<: *consul-agent
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"
    volumes:
      - consul-server-1:/consul/data

  consul-server-2:
    <<: *consul-server
    volumes:
      - consul-server-2:/consul/data

  consul-server-bootstrap:
    <<: *consul-agent
    environment:
      CONSUL_UI_BETA: "true"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"
    volumes:
      - consul-server-3:/consul/data