spring:
  mvc:
    favicon:
      enabled: false
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
server:
  port: 8080
logging:
  file: log.log
  level:
    org:
      springframework:
        web: DEBUG
