spring:
  redis:
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
    host: 127.0.0.1
    timeout: 0
server:
   name: scau-bbs-chat
   port: 8082
logging:
  level:
    org:
      springframework:
        web: DEBUG
