spring:
  http:
    multipart:
      max-file-size: 2MB
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  redis:
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
    host: 47.107.89.95
    timeout: 0
server:
  tomcat:
    uri-encoding: UTF-8
logging:
  level:
    org:
      springframework:
        web: DEBUG
